### ISSUE TITLE
Track Ironmen that were previously HCIM

### ISSUE THREAD

**Issue by ejaz-karim** [osrs-tracker/osrs-tracker-web#29]
It shows all the stats as negative, and doesn't track logs. Possibly because it is still trying to track the HCIM hiscores.

**Comment by FreekMencke** [comment]
@ejaz-karim can you give me an example player I can test this with? This shouldn't be the case unless the HCIM stats were tracked, but as an ironman the stats are yet untracked, and the hiscores then will return level `-1` and xp `-1`.

**Comment by ejaz-karim** [comment]
I have sent an email with the URL

**Comment by FreekMencke** [comment]
Alright, so it's happening because you account is not trackable in de regular osrs hiscores. You don't have high enough stats to appear in de default hiscores.

![image](https://github.com/osrs-tracker/osrs-tracker-web/assets/7610043/7ce99d3e-f092-4cd2-9943-e6e9f626bf0e)

I'm going to look into to this to fix it, but it's not going to be soon. This means I will have to do some structural changes to the XP Tracking code. When your stats are a bit higher, this problem will fix itself for you though.

**Comment by ejaz-karim** [comment]
I see, ironmen appear both in the regular and ironman hiscores but, if you know the account is an ironman why don't you just pull from the ironman hiscores?

**Comment by FreekMencke** [comment]
Because it would mean doing at least twice as many calls. Image the account type is harcore_ironman. I would have to fetch the hardcore ironman, regular ironman and default hiscores just to determine which hiscore I need. 

- If a hardcore_ironman died, the hiscores would still exist, but be lower (in levels/xp) as the regular ironman hiscores. 
- Same for de-ironed ironman, I would still have to compare the regular ironman hiscores with the normal hiscores to see if there is a difference.

Otherwise, using the default hiscores is always correct, the only disadvantage is that new accounts might not have high enough stats yet to be tracked.

In the future I might look into caching some stuff and using the specific hiscores, but for now I'm going to stick to using the default hiscores. Just look at it as extra motivation to get some gains that'll put you on the hiscores, good luck!
